name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Ensures full git history for `git pull`

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/trade-api
          git pull origin main
          
          # Stop and remove any existing containers
          docker stop trade-api || true
          docker rm trade-api || true
          
          # Remove old images to free space
          docker rmi trade-api || true
          
          # Build and run the new container
          docker build -t trade-api .
          docker run -d -p 8000:8000 trade-api
          
          # Show running containers
          docker ps
